package main;

public class Tables {

    static String agence = "CREATE TABLE public.agence "
            + "("
            + "    id character varying(40) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    name character varying(255) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    host character varying(17) DEFAULT '127.0.0.1',"
            + "    port int not null default 5432,"
            + "	database character varying(32) DEFAULT 'postgres' not null,"
            + "	username character varying(32) DEFAULT 'honyi' not null,"
            + "	password character varying(32) DEFAULT 'honyi123' not null,"
            + "    status int not null default 1,"
            + "    CONSTRAINT agence_pkey PRIMARY KEY (id)"
            + ")"
            + ";";
    static String cible = "create table cible("
            + "	biz_type_id character varying(32) not null,"
            + "	db_id character varying(40) not null references agence(id) ON DELETE CASCADE,"
            + "	cibleA NUMERIC DEFAULT 0,"
            + "	cibleT NUMERIC DEFAULT 0,"
            + "	dCible NUMERIC DEFAULT 0"
            + ");";
    static String lastupdate = "create table lastupdate ("
            + "	id_db  character varying(40) not null references agence(id) ON DELETE CASCADE,"
            + "    last_update timestamp(6) without time zone"
            + ");";
    static String t_biz_type = "CREATE TABLE public.t_biz_type"
            + "("
            + "    id character varying(32) ,"
            + "    name character varying(255) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    biz_prefix character varying(32) COLLATE pg_catalog.\"default\","
            + "    card_enable smallint,"
            + "    status smallint DEFAULT 1,"
            + "    mod_user character varying(20) COLLATE pg_catalog.\"default\","
            + "    mod_time timestamp(6) without time zone DEFAULT now(),"
            + "    auto_trans character varying(32) COLLATE pg_catalog.\"default\","
            + "    comments character varying(100) COLLATE pg_catalog.\"default\","
            + "    start_num character varying(10) COLLATE pg_catalog.\"default\","
            + "    sort smallint DEFAULT 0,"
            + "    call_delay smallint DEFAULT 0,"
            + "    info character varying(300) COLLATE pg_catalog.\"default\","
            + "    need_book smallint DEFAULT 0,"
            + "    biz_class_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    deal_time_warning integer,"
            + "    branch_id character varying(32) COLLATE pg_catalog.\"default\" DEFAULT 1,"
            + "    limit_by_ampm smallint DEFAULT 0,"
            + "    hidden smallint DEFAULT 0,"
            + "    biz_code character varying(100) COLLATE pg_catalog.\"default\","
            + "    external_code character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend1 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend2 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend3 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend4 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend5 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend6 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend7 character varying(100) COLLATE pg_catalog.\"default\","
            + "    db_id  character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String t_login_log = "CREATE TABLE public.t_login_log"
            + "("
            + "    id character varying(32) ,"
            + "    login_time timestamp(6) without time zone,"
            + "    login_type character varying(50) COLLATE pg_catalog.\"default\","
            + "    user_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    account character varying(100) COLLATE pg_catalog.\"default\","
            + "    login_source character varying(1000) COLLATE pg_catalog.\"default\","
            + "    logs character varying(4000) COLLATE pg_catalog.\"default\","
            + "    login_ip character varying(100) COLLATE pg_catalog.\"default\","
            + "    session_id character varying(4000) COLLATE pg_catalog.\"default\","
            + "    successed numeric(1,0),"
            + "    db_id  character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String t_ticket = ""
            + "CREATE TABLE public.t_ticket"
            + "("
            + "    id character varying(32) ,"
            + "    biz_type_id character varying(32) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    evaluation_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    ticket_id character varying(10) COLLATE pg_catalog.\"default\","
            + "    ticket_type character varying(32) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    status smallint NOT NULL,"
            + "    tag character varying(2) COLLATE pg_catalog.\"default\","
            + "    types_priority smallint DEFAULT 0,"
            + "    priority smallint DEFAULT 0,"
            + "    deal_win character varying(32) COLLATE pg_catalog.\"default\","
            + "    transfer_win character varying(32) COLLATE pg_catalog.\"default\","
            + "    deal_user character varying(20) COLLATE pg_catalog.\"default\","
            + "    book_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    call_language character varying(6) COLLATE pg_catalog.\"default\","
            + "    interrupt_long smallint DEFAULT 0,"
            + "    previous_book smallint,"
            + "    default_eval smallint DEFAULT 0,"
            + "    beizhu character varying(200) COLLATE pg_catalog.\"default\","
            + "    mark smallint,"
            + "    id_card_info_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    ticket_ser smallint,"
            + "    ticket_user character varying(255) COLLATE pg_catalog.\"default\","
            + "    eval_time timestamp(6) without time zone,"
            + "    ticket_time timestamp(6) without time zone,"
            + "    finish_time timestamp(6) without time zone,"
            + "    call_time timestamp(6) without time zone,"
            + "    start_time timestamp(6) without time zone,"
            + "    call_type character varying(255) COLLATE pg_catalog.\"default\" DEFAULT 1,"
            + "    branch_id character varying(32) COLLATE pg_catalog.\"default\" DEFAULT 1,"
            + "    id_card_name character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend1 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend2 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend3 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend4 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend5 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend6 character varying(100) COLLATE pg_catalog.\"default\","
            + "    extend7 character varying(100) COLLATE pg_catalog.\"default\","
            + "    db_id  character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String t_user = ""
            + "CREATE TABLE public.t_user"
            + "("
            + "    id character varying(32) ,"
            + "    account character varying(50) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    passwd character varying(1000) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    name character varying(100) COLLATE pg_catalog.\"default\","
            + "    nike_name character varying(100) COLLATE pg_catalog.\"default\","
            + "    limit_time timestamp(6) without time zone,"
            + "    access_time timestamp(6) without time zone,"
            + "    status numeric(1,0) DEFAULT 1,"
            + "    gender character varying(1) COLLATE pg_catalog.\"default\","
            + "    birthday timestamp(6) without time zone,"
            + "    mobile character varying(30) COLLATE pg_catalog.\"default\","
            + "    tel character varying(50) COLLATE pg_catalog.\"default\","
            + "    email character varying(50) COLLATE pg_catalog.\"default\","
            + "    addresss character varying(300) COLLATE pg_catalog.\"default\","
            + "    dept_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    usertype numeric(3,0),"
            + "    add_user character varying(32) COLLATE pg_catalog.\"default\","
            + "    add_time timestamp(6) without time zone,"
            + "    mod_user character varying(32) COLLATE pg_catalog.\"default\","
            + "    mod_time timestamp(6) without time zone,"
            + "    salt character varying(500) COLLATE pg_catalog.\"default\","
            + "    ip character varying(100) COLLATE pg_catalog.\"default\","
            + "    avatar character varying(300) COLLATE pg_catalog.\"default\","
            + "    work_num character varying(100) COLLATE pg_catalog.\"default\","
            + "    work character varying(100) COLLATE pg_catalog.\"default\","
            + "    star smallint,"
            + "db_id  character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String t_window = ""
            + "CREATE TABLE public.t_window"
            + "("
            + "    id character varying(32) ,"
            + "    win_number smallint,"
            + "    name character varying(255) COLLATE pg_catalog.\"default\","
            + "    com_name character varying(30) COLLATE pg_catalog.\"default\","
            + "    screen_address character varying(30) COLLATE pg_catalog.\"default\","
            + "    protocol character varying(32) COLLATE pg_catalog.\"default\","
            + "    enable_eval numeric(1,0),"
            + "    standard character varying(10) COLLATE pg_catalog.\"default\","
            + "    status smallint NOT NULL,"
            + "    mod_user character varying(20) COLLATE pg_catalog.\"default\","
            + "    mod_time timestamp(6) without time zone,"
            + "    screen_type character varying(10) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    win_group_id character varying(32) COLLATE pg_catalog.\"default\","
            + "    ip_address character varying(32) COLLATE pg_catalog.\"default\","
            + "    eval_address character varying(30) COLLATE pg_catalog.\"default\","
            + "    default_user character varying(32) COLLATE pg_catalog.\"default\","
            + "    ctrl_server character varying(32) COLLATE pg_catalog.\"default\","
            + "    beeper_addr character varying(32) COLLATE pg_catalog.\"default\","
            + "    sound_server character varying(32) COLLATE pg_catalog.\"default\","
            + "    branch_id character varying(32) COLLATE pg_catalog.\"default\","
            + "db_id  character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String t_window_status = "CREATE TABLE public.t_window_status"
            + "("
            + "    window_id character varying(32) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    user_id character varying(20) COLLATE pg_catalog.\"default\","
            + "    status numeric(1,0),"
            + "    access_time timestamp(6) without time zone,"
            + "    pause_count numeric(5,0),"
            + "    final_opernate_time timestamp(6) without time zone,"
            + "    ip character varying(32) COLLATE pg_catalog.\"default\","
            + "    win_puase_time timestamp(6) without time zone,"
            + "    batch_deal_status numeric(1,0),"
            + "    pause_time numeric(5,0),"
            + "    current_ticket character varying(32) COLLATE pg_catalog.\"default\","
            + "db_id  character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String task="CREATE TABLE rougga_task "
            + "("
            + "id character varying(40),"
            + "name character varying(255) not null,"
            + "id_service character varying(32),"
            + "db_id character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String ticket_task="CREATE TABLE rougga_ticket_task"
            + "("
            + "id_ticket character varying(32) ,"
            + "id_task  character varying(40) ,"
            + "quantity numeric(5,0) default 1,"
            + "db_id character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String task_central="CREATE TABLE rougga_task "
            + "("
            + "id character varying(40),"
            + "name character varying(255) not null,"
            + "id_service character varying(32) ,"
            + "db_id character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String ticket_task_cental="CREATE TABLE rougga_ticket_task"
            + "("
            + "id_ticket character varying(32) ,"
            + "id_task  character varying(40) ,"
            + "quantity numeric(5,0) default 1,"
            + "db_id character varying(40) not null references agence(id) ON DELETE CASCADE"
            + ");";
    static String rougga_zone = "CREATE TABLE public.rougga_zone "
            + "("
            + "    id character varying(40) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    name character varying(40) COLLATE pg_catalog.\"default\" NOT NULL,"
            + "    city character varying(40) ,"
            + "    code character varying(40) ,"
            + "    CONSTRAINT zone_pkey PRIMARY KEY (id)"
            + ")"
            + ";";
     static String rougga_agence_zone="CREATE TABLE rougga_agence_zone"
            + "("
            + "id_agence character varying(40) not null references agence(id) ON DELETE CASCADE,"
            + "id_zone  character varying(40) not null references rougga_zone(id) ON DELETE CASCADE "
            + ");";
    
}
